### PR TITLE
update the recycling bin option

### PR DESCRIPTION
**Pull request by cjerrington**
Powershell has a module in PS 5.1+ called Clear-Recyclebin that works better than the CMD method - rd /s %systemdrive%\$Recycle.bin

the -Force command cleans all $Recyle.Bin folders for all drives not just the %systemdrive% and the CMD method was missing the /q argument but this is not working in Windows 10. The Powershell method is more reliable.

### CODE REVIEW

**Comment by undergroundwires** [comment]
Hi @cjerrington 👋 Thanks for the PR and a very clear reasoning & explanation. It's a a great improvement and as you mentioned an improvement is definitely needed there.

> On the initial release of Windows 10, with automatic updates enabled, PowerShell gets updated from version 5.0 to 5.1. If the original version of Windows 10 is not updated through Windows Updates, the version of PowerShell is 5.0. | [Microsoft Docs](https://docs.microsoft.com/en-us/powershell/scripting/windows-powershell/install/installing-windows-powershell?view=powershell-7)

I'd guess that it would be nice to keep the scripts as backwards compatible as possible so it works in older Windows 10 versions. I know people running generated scripts in a Windows installation before updates.

So how about using this instead?

```ps1
$bin = (New-Object -ComObject Shell.Application).NameSpace(10); $bin.items() | ForEach { echo "Deleting $($_.path)"; rm $_.path -Recurse -Force }
```

As batch command:
```batchfile
Powershell -Command "$bin = (New-Object -ComObject Shell.Application).NameSpace(10); $bin.items() | ForEach { echo \"Deleting $($_.path)\"; rm $_.path -Recurse -Force }"
````

It might also be good to update the name to "Empty trash bin **on all drives**" to make it more explicit what it's doing.

**Comment by undergroundwires** [comment]
Hi @cjerrington 👋 Thanks for the PR and a very clear reasoning & explanation. It's a a great improvement and as you mentioned an improvement is definitely needed there.

> On the initial release of Windows 10, with automatic updates enabled, PowerShell gets updated from version 5.0 to 5.1. If the original version of Windows 10 is not updated through Windows Updates, the version of PowerShell is 5.0. | [Microsoft Docs](https://docs.microsoft.com/en-us/powershell/scripting/windows-powershell/install/installing-windows-powershell?view=powershell-7)

I'd guess that it would be nice to keep the scripts as backwards compatible as possible so it works in older Windows 10 versions. I know people running generated scripts in a Windows installation before updates.

So how about using this instead?

```ps1
$bin = (New-Object -ComObject Shell.Application).NameSpace(10);
$bin.items() | ForEach {
  echo "Deleting $($_.path)";
  rm $_.path -Recurse -Force
}
```

As batch command:
```batchfile
Powershell -Command "$bin = (New-Object -ComObject Shell.Application).NameSpace(10); $bin.items() | ForEach { echo \"Deleting $($_.path)\"; rm $_.path -Recurse -Force }"
````

It might also be good to update the name to "Empty trash bin **on all drives**" to make it more explicit what it's doing.

**Comment by cjerrington** [comment]
Now that you point that out, I do agree your suggestion is better at backwards compatibility. It is better to use the Full Commandlet name instead of aliases. 

Changed `echo` to `Write-Host` and `rm` to `Remove-Item`. If someone had different aliases set for these it might have adverse affects. 

```powershell 
$bin = (New-Object -ComObject Shell.Application).NameSpace(10);
$bin.items() | ForEach {
  Write-Host "Deleting $($_.Name) from Recycle Bin";
  Remove-Item $_.Path -Recurse -Force
}
```

We can echo the name of the file instead of the path since the path has a temporary name, but can call the `$_.Name` property to get the actual file or folder name. We still need full Path when calling `Remove-Item`. 

Calling the ComObject like this will only get the system recycling bin and not all drives like the `Clear-Recyclebin` function can do for all fixed drives.

**Comment by undergroundwires** [comment]
🍻 Great job, you should probably review my PRs instead of I do yours, much better than I initially though. Thanks again, very much appreciated. ♥

**Comment by undergroundwires** [comment]
🍻 Great job, you should probably review my PRs instead of I do yours, much better than I initially though. Thanks again, very much appreciated. I'll do a release in the weekend along with some other bug fixes.

**Pull request merged**
