### PR TITLE
Added "Disable Bing search suggestions in Start Menu"

### PR DESCRIPTION
**Pull request by Permanently**
Hello again 👋 thought I'd add since some people (myself included) don't want to use Bing at all.

Added "Disable Bing search suggestions in Start Menu"
- Adds DisableSearchBoxSuggestions registry key
- Restarts explorer.exe to apply changes

### CODE REVIEW

**Comment by undergroundwires** [comment]
What a great contribution! I have nothing to add but just admire your choices. I think everything looks good.

I'll do a patch release in a week and two and then a minor release with new scripts and some other cool improvements, so I'll merge this after the patch is out.

I have messed up by this PR by force-pushing on master. I really don't like how GitHub handles this. But no worries, I'll fix it (rebase this back on master) before merging.

Thank you, hope to see you around more 👍️

**Comment by undergroundwires** [comment]
Microsoft seems to retire `BingSearchEnabled` and replace it with `DisableSearchBoxSuggestions` [1] [2] [3] . I've tested this on W10 and W11 and it works as expected. This also aligns with some community testing done in Disassembler0/Win10-Initial-Setup-Script#300 .

Interestingly, Microsoft documents this setting as [4] [5] :

> If you enable this policy, File Explorer will not show suggestion pop-ups as users type into the Search Box, and it will not store Search Box entries into the registry for future references. If the user types a property, values that match this property will be shown but no data will be saved in the registry or re-shown on subsequent uses of the search box.

Thank you for `kill explorer` command that made it easier when testing but I think restarting explorer.exe suddenly may be irritating to the user that does not expect this. These scripts are used in very different ways and sometimes in automated manner, so let's just remove that part. I also change `reg add` to `reg delete` for reverting to match default OS behavior. Unfortunately all scripts do not match default OS behavior but good to take consideration into it for new scripts. I'll document this in `CONTRIBUTING.md`.

Your categorization is better, I'll move some other (legacy) scripts and group together on this category.

[1]: https://www.windowslatest.com/2020/10/04/disable-bing-in-windows-search/
[2]: https://borncity.com/win/2020/10/05/windows-10-disable-bing-in-the-search/
[3]: https://www.techbout.com/disable-web-results-in-windows-search-44034/
[4]: https://admx.help/?Category=Windows_10_2016&Policy=Microsoft.Policies.WindowsExplorer::DisableSearchBoxSuggestions
[5]: https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-admx-windowsexplorer#admx-windowsexplorer-disablesearchboxsuggestions

**Comment by undergroundwires** [comment]
@Permanently , could you review my changes and give feedback?

I added some more docs, converted explorer.exe into a warning, regrouped other similar scripts onto the same category and use `reg delete` when reverting.

The category has now 4 scripts, 3 being old ones, and the first one is the one you add with this PR that works with latest Windows:



The script looks like this:





Once executed, it looks like this:

**Comment by Permanently** [comment]
Looks good - I would personally take it a step further and add a tickbox under the option to restart explorer.exe. That way, someone can choose either to restart explorer.exe manually, or have the script do it for them. Obviously keep it disabled by default, but it opens up the open for lazy people (like me) ;)

**Comment by undergroundwires** [comment]
Thanks. How about this..

1. On scripts that requires explorer.exe restart we set `requires_explorer_restart=true`. 
2. In "Advanced settings" category (last one) we add a special script "Restart explorer.exe if required" but do not recommended it. This special script would check if `requires_explorer_restart` is defined and is `true` by any other script before, and if it's the case it would restart the explorer.exe?

This way, we introduce a reusable solution, non-intrusive default configuration and still let power users like you to enable it. It introduces a bit of complexity due to scripts communicating with each other through variables that would have potential side-effects but I think this is worth the complexity.

If it makes sense, I will revert back e74ee45 that shows the warning. We can then merge this PR, and create another one to introduce that.

**Comment by undergroundwires** [comment]
@Permanently Fuck. I made a mistake and lost this code when I was merging this, GitHub CLI ruined this... I do not see this on your branch either. Do you have it somewhere?

Sorry for merging this late. I was thinking of making feature releases for new scripts but its taking too much time so I'll add new script as part of new patches.

**Comment by undergroundwires** [comment]
@Permanently I made a mistake and lost this code when I was merging this, GitHub CLI ruined this.

I will merge this manually. Sorry for merging this late. I was thinking of making feature releases for new scripts but its taking too much time so I'll add new script as part of new patches.

**Comment by Permanently** [comment]
No worries - if you still have the registry key then it shouldn't be hard to add in anyway. Just take another registry key modification script and whack it in.

**Pull request merged**
