### PR TITLE
a few missing things

### PR DESCRIPTION
**Pull request by sopla4ever**
added option for:
- disable tls10, tls11, dtls10, dtls11, ssl2, ssl3, md5, rc2, rc4, des, 3des, null ciphers and netbios
- enable strong auth for net apps, tls13, dtls13, 4096bit dhk

### CODE REVIEW

**Review by undergroundwires — CHANGES_REQUESTED** [review]
Wow. This is awesome. Great job really! 🎉 The categories, naming, syntax, code all look good! Also I double checked the scripts, not only that their code is doing the right thing but also your choices are very strategic to disable all the weak legacy stuff and enforcing best practices 👍  I see a mind who knows what he's doing here.

There are very minor stuff that I commented on that we should resolve than I believe we can merge this and release by the next version.

**Comment by sopla4ever** [comment]
Thank you for correcting the code after me.

There is another important change in registry but i don't know how to add hex value via CMD.

Following cipher suites are enabled by default on build 20236.1005 (insider):
- TLS_AES_256_GCM_SHA384
- TLS_AES_128_GCM_SHA256
- TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
- TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
- TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
- TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
- TLS_DHE_RSA_WITH_AES_256_GCM_SHA384
- TLS_DHE_RSA_WITH_AES_128_GCM_SHA256
- TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384
- TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
- TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
- TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
- TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA
- TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA
- TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
- TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
- TLS_RSA_WITH_AES_256_GCM_SHA384
- TLS_RSA_WITH_AES_128_GCM_SHA256
- TLS_RSA_WITH_AES_256_CBC_SHA256
- TLS_RSA_WITH_AES_128_CBC_SHA256
- TLS_RSA_WITH_AES_256_CBC_SHA
- TLS_RSA_WITH_AES_128_CBC_SHA
- TLS_RSA_WITH_3DES_EDE_CBC_SHA
- TLS_RSA_WITH_NULL_SHA256
- TLS_RSA_WITH_NULL_SHA
- TLS_PSK_WITH_AES_256_GCM_SHA384
- TLS_PSK_WITH_AES_128_GCM_SHA256
- TLS_PSK_WITH_AES_256_CBC_SHA384
- TLS_PSK_WITH_AES_128_CBC_SHA256
- TLS_PSK_WITH_NULL_SHA384
- TLS_PSK_WITH_NULL_SHA256

```
; default 20236.1005
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Cryptography\Configuration\Local\SSL\00010002]
"Functions"=hex(7):54,00,4c,00,53,00,5f,00,41,00,45,00,53,00,5f,00,32,00,35,00,\
  36,00,5f,00,47,00,43,00,4d,00,5f,00,53,00,48,00,41,00,33,00,38,00,34,00,00,\
  00,54,00,4c,00,53,00,5f,00,41,00,45,00,53,00,5f,00,31,00,32,00,38,00,5f,00,\
  47,00,43,00,4d,00,5f,00,53,00,48,00,41,00,32,00,35,00,36,00,00,00,54,00,4c,\
  00,53,00,5f,00,45,00,43,00,44,00,48,00,45,00,5f,00,45,00,43,00,44,00,53,00,\
  41,00,5f,00,57,00,49,00,54,00,48,00,5f,00,41,00,45,00,53,00,5f,00,32,00,35,\
  00,36,00,5f,00,47,00,43,00,4d,00,5f,00,53,00,48,00,41,00,33,00,38,00,34,00,\
  00,00,54,00,4c,00,53,00,5f,00,45,00,43,00,44,00,48,00,45,00,5f,00,45,00,43,\
  00,44,00,53,00,41,00,5f,00,57,00,49,00,54,00,48,00,5f,00,41,00,45,00,53,00,\
  5f,00,31,00,32,00,38,00,5f,00,47,00,43,00,4d,00,5f,00,53,00,48,00,41,00,32,\
  00,35,00,36,00,00,00,54,00,4c,00,53,00,5f,00,45,00,43,00,44,00,48,00,45,00,\
  5f,00,52,00,53,00,41,00,5f,00,57,00,49,00,54,00,48,00,5f,00,41,00,45,00,53,\
  00,5f,00,32,00,35,00,36,00,5f,00,47,00,43,00,4d,00,5f,00,53,00,48,00,41,00,\
  33,00,38,00,34,00,00,00,54,00,4c,00,53,00,5f,00,45,00,43,00,44,00,48,00,45,\
  00,5f,00,52,00,53,00,41,00,5f,00,57,00,49,00,54,00,48,00,5f,00,41,00,45,00,\
  53,00,5f,00,31,00,32,00,38,00,5f,00,47,00,43,00,4d,00,5f,00,53,00,48,00,41,\
  00,32,00,35,00,36,00,00,00,54,00,4c,00,53,00,5f,00,44,00,48,00,45,00,5f,00,\
  52,00,53,00,41,00,5f,00,57,00,49,00,54,00,48,00,5f,00,41,00,45,00,53,00,5f,\
  00,32,00,35,00,36,00,5f,00,47,00,43,00,4d,00,5f,00,53,00,48,00,41,00,33,00,\
  38,00,34,00,00,00,54,00,4c,00,53,00,5f,00,44,00,48,00,45,00,5f,00,52,00,53,\
  00,41,00,5f,00,57,00,49,00,54,00,48,00,5f,00,41,00,45,00,53,00,5f,00,31,00,\
  32,00,38,00,5f,00,47,00,43,00,4d,00,5f,00,53,00,48,00,41,00,32,00,35,00,36,\
  00,00,00,54,00,4c,00,53,00,5f,00,45,00,43,00,44,00,48,00,45,00,5f,00,45,00,\
  43,00,44,00,53,00,41,00,5f,00,57,00,49,00,54,00,48,00,5f,00,41,00,45,00,53,\
  00,5f,00,32,00,35,00,36,00,5f,00,43,00,42,00,43,00,5f,00,53,00,48,00,41,00,\
  33,00,38,00,34,00,00,00,54,00,4c,00,53,00,5f,00,45,00,43,00,44,00,48,00,45,\
  00,5f,00,45,00,43,00,44,00,53,00,41,00,5f,00,57,00,49,00,54,00,48,00,5f,00,\
  41,00,45,00,53,00,5f,00,31,00,32,00,38,00,5f,00,43,00,42,00,43,00,5f,00,53,\
  00,48,00,41,00,32,00,35,00,36,00,00,00,54,00,4c,00,53,00,5f,00,45,00,43,00,\
  44,00,48,00,45,00,5f,00,52,00,53,00,41,00,5f,00,57,00,49,00,54,00,48,00,5f,\
  00,41,00,45,00,53,00,5f,00,32,00,35,00,36,00,5f,00,43,00,42,00,43,00,5f,00,\
  53,00,48,00,41,00,33,00,38,00,34,00,00,00,54,00,4c,00,53,00,5f,00,45,00,43,\
  00,44,00,48,00,45,00,5f,00,52,00,53,00,41,00,5f,00,57,00,49,00,54,00,48,00,\
  5f,00,41,00,45,00,53,00,5f,00,31,00,32,00,38,00,5f,00,43,00,42,00,43,00,5f,\
  00,53,00,48,00,41,00,32,00,35,00,36,00,00,00,54,00,4c,00,53,00,5f,00,45,00,\
  43,00,44,00,48,00,45,00,5f,00,45,00,43,00,44,00,53,00,41,00,5f,00,57,00,49,\
  00,54,00,48,00,5f,00,41,00,45,00,53,00,5f,00,32,00,35,00,36,00,5f,00,43,00,\
  42,00,43,00,5f,00,53,00,48,00,41,00,00,00,54,00,4c,00,53,00,5f,00,45,00,43,\
  00,44,00,48,00,45,00,5f,00,45,00,43,00,44,00,53,00,41,00,5f,00,57,00,49,00,\
  54,00,48,00,5f,00,41,00,45,00,53,00,5f,00,31,00,32,00,38,00,5f,00,43,00,42,\
  00,43,00,5f,00,53,00,48,00,41,00,00,00,54,00,4c,00,53,00,5f,00,45,00,43,00,\
  44,00,48,00,45,00,5f,00,52,00,53,00,41,00,5f,00,57,00,49,00,54,00,48,00,5f,\
  00,41,00,45,00,53,00,5f,00,32,00,35,00,36,00,5f,00,43,00,42,00,43,00,5f,00,\
  53,00,48,00,41,00,00,00,54,00,4c,00,53,00,5f,00,45,00,43,00,44,00,48,00,45,\
  00,5f,00,52,00,53,00,41,00,5f,00,57,00,49,00,54,00,48,00,5f,00,41,00,45,00,\
  53,00,5f,00,31,00,32,00,38,00,5f,00,43,00,42,00,43,00,5f,00,53,00,48,00,41,\
  00,00,00,54,00,4c,00,53,00,5f,00,52,00,53,00,41,00,5f,00,57,00,49,00,54,00,\
  48,00,5f,00,41,00,45,00,53,00,5f,00,32,00,35,00,36,00,5f,00,47,00,43,00,4d,\
  00,5f,00,53,00,48,00,41,00,33,00,38,00,34,00,00,00,54,00,4c,00,53,00,5f,00,\
  52,00,53,00,41,00,5f,00,57,00,49,00,54,00,48,00,5f,00,41,00,45,00,53,00,5f,\
  00,31,00,32,00,38,00,5f,00,47,00,43,00,4d,00,5f,00,53,00,48,00,41,00,32,00,\
  35,00,36,00,00,00,54,00,4c,00,53,00,5f,00,52,00,53,00,41,00,5f,00,57,00,49,\
  00,54,00,48,00,5f,00,41,00,45,00,53,00,5f,00,32,00,35,00,36,00,5f,00,43,00,\
  42,00,43,00,5f,00,53,00,48,00,41,00,32,00,35,00,36,00,00,00,54,00,4c,00,53,\
  00,5f,00,52,00,53,00,41,00,5f,00,57,00,49,00,54,00,48,00,5f,00,41,00,45,00,\
  53,00,5f,00,31,00,32,00,38,00,5f,00,43,00,42,00,43,00,5f,00,53,00,48,00,41,\
  00,32,00,35,00,36,00,00,00,54,00,4c,00,53,00,5f,00,52,00,53,00,41,00,5f,00,\
  57,00,49,00,54,00,48,00,5f,00,41,00,45,00,53,00,5f,00,32,00,35,00,36,00,5f,\
  00,43,00,42,00,43,00,5f,00,53,00,48,00,41,00,00,00,54,00,4c,00,53,00,5f,00,\
  52,00,53,00,41,00,5f,00,57,00,49,00,54,00,48,00,5f,00,41,00,45,00,53,00,5f,\
  00,31,00,32,00,38,00,5f,00,43,00,42,00,43,00,5f,00,53,00,48,00,41,00,00,00,\
  54,00,4c,00,53,00,5f,00,52,00,53,00,41,00,5f,00,57,00,49,00,54,00,48,00,5f,\
  00,33,00,44,00,45,00,53,00,5f,00,45,00,44,00,45,00,5f,00,43,00,42,00,43,00,\
  5f,00,53,00,48,00,41,00,00,00,54,00,4c,00,53,00,5f,00,52,00,53,00,41,00,5f,\
  00,57,00,49,00,54,00,48,00,5f,00,4e,00,55,00,4c,00,4c,00,5f,00,53,00,48,00,\
  41,00,32,00,35,00,36,00,00,00,54,00,4c,00,53,00,5f,00,52,00,53,00,41,00,5f,\
  00,57,00,49,00,54,00,48,00,5f,00,4e,00,55,00,4c,00,4c,00,5f,00,53,00,48,00,\
  41,00,00,00,54,00,4c,00,53,00,5f,00,50,00,53,00,4b,00,5f,00,57,00,49,00,54,\
  00,48,00,5f,00,41,00,45,00,53,00,5f,00,32,00,35,00,36,00,5f,00,47,00,43,00,\
  4d,00,5f,00,53,00,48,00,41,00,33,00,38,00,34,00,00,00,54,00,4c,00,53,00,5f,\
  00,50,00,53,00,4b,00,5f,00,57,00,49,00,54,00,48,00,5f,00,41,00,45,00,53,00,\
  5f,00,31,00,32,00,38,00,5f,00,47,00,43,00,4d,00,5f,00,53,00,48,00,41,00,32,\
  00,35,00,36,00,00,00,54,00,4c,00,53,00,5f,00,50,00,53,00,4b,00,5f,00,57,00,\
  49,00,54,00,48,00,5f,00,41,00,45,00,53,00,5f,00,32,00,35,00,36,00,5f,00,43,\
  00,42,00,43,00,5f,00,53,00,48,00,41,00,33,00,38,00,34,00,00,00,54,00,4c,00,\
  53,00,5f,00,50,00,53,00,4b,00,5f,00,57,00,49,00,54,00,48,00,5f,00,41,00,45,\
  00,53,00,5f,00,31,00,32,00,38,00,5f,00,43,00,42,00,43,00,5f,00,53,00,48,00,\
  41,00,32,00,35,00,36,00,00,00,54,00,4c,00,53,00,5f,00,50,00,53,00,4b,00,5f,\
  00,57,00,49,00,54,00,48,00,5f,00,4e,00,55,00,4c,00,4c,00,5f,00,53,00,48,00,\
  41,00,33,00,38,00,34,00,00,00,54,00,4c,00,53,00,5f,00,50,00,53,00,4b,00,5f,\
  00,57,00,49,00,54,00,48,00,5f,00,4e,00,55,00,4c,00,4c,00,5f,00,53,00,48,00,\
  41,00,32,00,35,00,36,00,00,00,00,00
```


**We should disable at least below:
- TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
- TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
- TLS_RSA_WITH_AES_128_GCM_SHA256
- TLS_RSA_WITH_AES_256_GCM_SHA384
- TLS_RSA_WITH_AES_128_CBC_SHA
- TLS_RSA_WITH_AES_256_CBC_SHA
- TLS_RSA_WITH_3DES_EDE_CBC_SHA
- TLS_RSA_WITH_NULL_SHA256
- TLS_RSA_WITH_NULL_SHA
- TLS_PSK_WITH_NULL_SHA384
- TLS_PSK_WITH_NULL_SHA256**

Hex for this modification disabling them with addition TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384_P521:
```
"Functions"=hex(7):54,00,4c,00,53,00,5f,00,41,00,45,00,53,00,5f,00,32,00,35,00,\
  36,00,5f,00,47,00,43,00,4d,00,5f,00,53,00,48,00,41,00,33,00,38,00,34,00,00,\
  00,54,00,4c,00,53,00,5f,00,41,00,45,00,53,00,5f,00,31,00,32,00,38,00,5f,00,\
  47,00,43,00,4d,00,5f,00,53,00,48,00,41,00,32,00,35,00,36,00,00,00,54,00,4c,\
  00,53,00,5f,00,45,00,43,00,44,00,48,00,45,00,5f,00,45,00,43,00,44,00,53,00,\
  41,00,5f,00,57,00,49,00,54,00,48,00,5f,00,41,00,45,00,53,00,5f,00,32,00,35,\
  00,36,00,5f,00,47,00,43,00,4d,00,5f,00,53,00,48,00,41,00,33,00,38,00,34,00,\
  00,00,54,00,4c,00,53,00,5f,00,45,00,43,00,44,00,48,00,45,00,5f,00,45,00,43,\
  00,44,00,53,00,41,00,5f,00,57,00,49,00,54,00,48,00,5f,00,41,00,54,00,4c,00,\
  53,00,5f,00,45,00,43,00,44,00,48,00,45,00,5f,00,52,00,53,00,41,00,5f,00,57,\
  00,49,00,54,00,48,00,5f,00,41,00,45,00,53,00,5f,00,31,00,32,00,38,00,5f,00,\
  43,00,42,00,43,00,5f,00,53,00,48,00,41,00,45,00,53,00,5f,00,31,00,32,00,38,\
  00,5f,00,47,00,43,00,4d,00,5f,00,53,00,48,00,41,00,32,00,35,00,36,00,00,00,\
  54,00,4c,00,53,00,5f,00,45,00,43,00,44,00,48,00,45,00,5f,00,52,00,53,00,41,\
  00,5f,00,57,00,49,00,54,00,48,00,5f,00,41,00,45,00,53,00,5f,00,32,00,35,00,\
  36,00,5f,00,47,00,43,00,4d,00,5f,00,53,00,48,00,41,00,33,00,38,00,34,00,00,\
  00,54,00,4c,00,53,00,5f,00,45,00,43,00,44,00,48,00,45,00,5f,00,52,00,53,00,\
  41,00,5f,00,57,00,49,00,54,00,48,00,5f,00,41,00,45,00,53,00,5f,00,31,00,32,\
  00,38,00,5f,00,47,00,43,00,4d,00,5f,00,53,00,48,00,41,00,32,00,35,00,36,00,\
  00,00,54,00,4c,00,53,00,5f,00,44,00,48,00,45,00,5f,00,52,00,53,00,41,00,5f,\
  00,57,00,49,00,54,00,48,00,5f,00,41,00,45,00,53,00,5f,00,32,00,35,00,36,00,\
  5f,00,47,00,43,00,4d,00,5f,00,53,00,48,00,41,00,33,00,38,00,34,00,00,00,54,\
  00,4c,00,53,00,5f,00,44,00,48,00,45,00,5f,00,52,00,53,00,41,00,5f,00,57,00,\
  49,00,54,00,48,00,5f,00,41,00,45,00,53,00,5f,00,31,00,32,00,38,00,5f,00,47,\
  00,43,00,4d,00,5f,00,53,00,48,00,41,00,32,00,35,00,36,00,00,00,54,00,4c,00,\
  53,00,5f,00,45,00,43,00,44,00,48,00,45,00,5f,00,45,00,43,00,44,00,53,00,41,\
  00,5f,00,57,00,49,00,54,00,48,00,5f,00,41,00,45,00,53,00,5f,00,32,00,35,00,\
  36,00,5f,00,43,00,42,00,43,00,5f,00,53,00,48,00,41,00,33,00,38,00,34,00,00,\
  00,54,00,4c,00,53,00,5f,00,45,00,43,00,44,00,48,00,45,00,5f,00,45,00,43,00,\
  44,00,53,00,41,00,5f,00,57,00,49,00,54,00,48,00,5f,00,41,00,45,00,53,00,5f,\
  00,31,00,32,00,38,00,5f,00,43,00,42,00,43,00,5f,00,53,00,48,00,41,00,32,00,\
  35,00,36,00,00,00,54,00,4c,00,53,00,5f,00,45,00,43,00,44,00,48,00,45,00,5f,\
  00,52,00,53,00,41,00,5f,00,57,00,49,00,54,00,48,00,5f,00,41,00,45,00,53,00,\
  5f,00,32,00,35,00,36,00,5f,00,43,00,42,00,43,00,5f,00,53,00,48,00,41,00,33,\
  00,38,00,34,00,5f,00,50,00,35,00,32,00,31,00,00,00,54,00,4c,00,53,00,5f,00,\
  45,00,43,00,44,00,48,00,45,00,5f,00,52,00,53,00,41,00,5f,00,57,00,49,00,54,\
  00,48,00,5f,00,41,00,45,00,53,00,5f,00,32,00,35,00,36,00,5f,00,43,00,42,00,\
  43,00,5f,00,53,00,48,00,41,00,33,00,38,00,34,00,00,00,54,00,4c,00,53,00,5f,\
  00,45,00,43,00,44,00,48,00,45,00,5f,00,52,00,53,00,41,00,5f,00,57,00,49,00,\
  54,00,48,00,5f,00,41,00,45,00,53,00,5f,00,31,00,32,00,38,00,5f,00,43,00,42,\
  00,43,00,5f,00,53,00,48,00,41,00,32,00,35,00,36,00,00,00,54,00,4c,00,53,00,\
  5f,00,45,00,43,00,44,00,48,00,45,00,5f,00,45,00,43,00,44,00,53,00,41,00,5f,\
  00,57,00,49,00,54,00,48,00,5f,00,41,00,45,00,53,00,5f,00,32,00,35,00,36,00,\
  5f,00,43,00,42,00,43,00,5f,00,53,00,48,00,41,00,00,00,54,00,4c,00,53,00,5f,\
  00,45,00,43,00,44,00,48,00,45,00,5f,00,45,00,43,00,44,00,53,00,41,00,5f,00,\
  57,00,49,00,54,00,48,00,5f,00,41,00,45,00,53,00,5f,00,31,00,32,00,38,00,5f,\
  00,43,00,42,00,43,00,5f,00,53,00,48,00,41,00,00,00,54,00,4c,00,53,00,5f,00,\
  52,00,53,00,41,00,5f,00,57,00,49,00,54,00,48,00,5f,00,41,00,45,00,53,00,5f,\
  00,32,00,35,00,36,00,5f,00,43,00,42,00,43,00,5f,00,53,00,48,00,41,00,32,00,\
  35,00,36,00,00,00,54,00,4c,00,53,00,5f,00,52,00,53,00,41,00,5f,00,57,00,49,\
  00,54,00,48,00,5f,00,41,00,45,00,53,00,5f,00,31,00,32,00,38,00,5f,00,43,00,\
  42,00,43,00,5f,00,53,00,48,00,41,00,32,00,35,00,36,00,00,00,54,00,4c,00,53,\
  00,5f,00,50,00,53,00,4b,00,5f,00,57,00,49,00,54,00,48,00,5f,00,41,00,45,00,\
  53,00,5f,00,32,00,35,00,36,00,5f,00,47,00,43,00,4d,00,5f,00,53,00,48,00,41,\
  00,33,00,38,00,34,00,00,00,54,00,4c,00,53,00,5f,00,50,00,53,00,4b,00,5f,00,\
  57,00,49,00,54,00,48,00,5f,00,41,00,45,00,53,00,5f,00,31,00,32,00,38,00,5f,\
  00,47,00,43,00,4d,00,5f,00,53,00,48,00,41,00,32,00,35,00,36,00,00,00,54,00,\
  4c,00,53,00,5f,00,50,00,53,00,4b,00,5f,00,57,00,49,00,54,00,48,00,5f,00,41,\
  00,45,00,53,00,5f,00,32,00,35,00,36,00,5f,00,43,00,42,00,43,00,5f,00,53,00,\
  48,00,41,00,33,00,38,00,34,00,00,00,54,00,4c,00,53,00,5f,00,50,00,53,00,4b,\
  00,5f,00,57,00,49,00,54,00,48,00,5f,00,41,00,45,00,53,00,5f,00,31,00,32,00,\
  38,00,5f,00,43,00,42,00,43,00,5f,00,53,00,48,00,41,00,32,00,35,00,36,00,00,\
  00,00,00
```

In addition, I'm not sure this default order is correct.


BTW, how to change launch parameters in existing shortcut?
By default Chrome (88.0.4298.5) has enabled some weak cipher suites. You can check browser  https://www.ssllabs.com/ssltest/viewMyClient.html and https://browserleaks.com/ssl

Due to the poor configuration of Chrome in about: flags, you need to add launch parameters to the shortcut from which you start the browser.
` --cipher-suite-blacklist=0xc013,0xc014,0x009c,0x009d,0x002f,0x0035,0x000a,0x0009c,0x0009d,0x0002f,0x00035
`

**Review by undergroundwires — APPROVED** [review]

**Comment by undergroundwires** [comment]
As a last step I was thinking about renaming the category to `Increase cryptography for IIS on Windows Server`. Does it sound correct? As I understand scripts (except NetBios) configure IIS only. And I'd also guess they only work on Windows Server, or would they work on Windows Home/Pro as well?

> Applying hex using batch/PowerShell

I don't know how we should add hex values either. I could not resolve #26 because of the same reason. 🤔

> Chrome command

Sad that the solution does not persist. I don't think there's a easy way to change shortcut commands as shortcut can be placed simply anywhere.

**Comment by sopla4ever** [comment]
Yes this is for IIS but most of them can be applied on client versions of windows

**Comment by undergroundwires** [comment]
Thanks for the clarification @sopla4ever , I just change the title to "Increase cryptography on ISS". I see that you improved more parts, the camera setting is awesome 🙏🏽 I'll merge this PR today and will do a release probably during the weekend, so feel free to create new PRs for new stuff and thanks for collaborating!

**Comment by undergroundwires** [comment]
Hi @sopla4ever , was ToDo app installed automatically by Microsoft and installed manually by you?

**Comment by sopla4ever** [comment]
Hi @undergroundwires , ToDo app is automatically installed from branch 2103 / 21H1

**Pull request merged**
