### PR TITLE
Fix Disable automatic updates (revert)

### PR DESCRIPTION
**Pull request by SnowzNZ**

### CODE REVIEW

**Comment by SnowzNZ** [comment]
Closing as will be fixed in #215 
https://github.com/undergroundwires/privacy.sexy/pull/215#issuecomment-1659371210

**Comment by undergroundwires** [comment]
Hi @SnowzNZ , I want to merge this before the other one. Could you re-open this?

**Comment by SnowzNZ** [comment]
Hi @undergroundwires do you still want this to be reopened?

**Comment by undergroundwires** [comment]
Hi @SnowzNZ sorry for deleting my comment and thanks for asking and your contribution. I was unsure how to go with this. I want to write a global function for registry adding and deleting on revert so these kind of issues do not happen again. That would obsolete both PRs. However it takes a lot of time and unsure when I'll be done. Can we re-open this so I can just merge if I lack the time refactor all reg add logic?

**Comment by SnowzNZ** [comment]
> Hi @SnowzNZ sorry for deleting my comment and thanks for asking and your contribution. I was unsure how to go with this. I want to write a global function for registry adding and deleting on revert so these kind of issues do not happen again. That would obsolete both PRs. However it takes a lot of time and unsure when I'll be done. Can we re-open this so I can just merge if I lack the time refactor all reg add logic?

Reopened in #234
Accidentally deleted the branch, sorry for the inconvenience

**Comment by SnowzNZ** [comment]
> Hi @SnowzNZ sorry for deleting my comment and thanks for asking and your contribution. I was unsure how to go with this. I want to write a global function for registry adding and deleting on revert so these kind of issues do not happen again. That would obsolete both PRs. However it takes a lot of time and unsure when I'll be done. Can we re-open this so I can just merge if I lack the time refactor all reg add logic?

Reopened in #234
Accidentally deleted the branch, sorry for the inconvenience

**Pull request closed without merging**
