### PR TITLE
Add GroupMe and Spotify removal option

### PR DESCRIPTION
**Pull request by CharlesZ54**

### CODE REVIEW

**Comment by undergroundwires** [comment]
Hi @CharlesZ54 , thanks for the PR 🎉, it actually looks pretty good. I'd like to merge this.

**Comment by CharlesZ54** [comment]
Okay, sounds good! One check failed last time but I wasn't sure how to fix it. Glad it seems to be working now.

**Comment by undergroundwires** [comment]
It was a security check (`npm audit`) that was failing because of an old dependency and is resolved now. Nothing wrong with your PR but good attention to detail btw. Now my force pushes has caused some conflicts 🤷‍♂️. But no worries, I'll fix the conflicts in the PR and merge it when I have time. It'll be in the next release. Thanks again 👍🏿

**Comment by undergroundwires** [comment]
Hi @CharlesZ54, just a question. I realized that Microsoft automatically installs Spotify app. Was it the same for GroupMe? Did you install it manually or was it installed automatically? Thanks!

**Pull request merged**
