### PR TITLE
Minor improvements

### PR DESCRIPTION
**Pull request by sopla4ever**
Added:

- disabling CPU core parking
- disabling Optimize Drive Schedule
- Windows Evaluation Rearm for 360 days
- Re-Enable option Image sharpening with DCH drivers in Nvidia Control Panel
- Missing Windows Power plans: Power saver, High performance and Ultimate Performance
- View All Power Plan Settings

### CODE REVIEW

**Comment by undergroundwires** [comment]
Hi, thanks again @sopla4ever, great effort again and very clean job & production grade quality. Unfortunately, something is wrong with this PR technically (not because of your changeS). As it is now it tries to re-add increase IIS that we already merged.

**Background**
The PR is done from the`master` of your fork [(spola4ever/privacy.sexy)](https://github.com/sopla4ever/privacy.sexy) which already had some changes compared to `master` here ([undergroundwires/privacy.sexy](https://github.com/undergroundwires/privacy.sexy)).

**Best-practice**
To avoid it, the the best practice is to create different branches for each change in your fork and then do the changes in respective branches and send PR for each. If it feels complicated, another option is to delete your fork and recreate it to get a fresh new master and then do your changes and send a PR. 

**Solution now**
So I recommend you to delete your fork and recreate it for future changes as your master is now "dirty" as it differs from current privacy.sexy master which leads to unintended changes in your PRs. If you don't do that then all of your future PRs will be dirty as this one.

**Question about tweaks**
Also regarding the tweaks, even though I believe they are pretty good OS customisations for advanced users I'm not sure how they would help with privacy or security. The goal is privacy.sexy is to stay focused on privacy/security. I might be wrong here, please correct me if they can be related to privacy/security somehow.

I see in the community that there's a big interest for a central OS configurator, not only for privacy. We could maybe fork this project, create a new project that would not be privacy focused and would be more "general purpose" OS tweaker. But it would consume time and effort from me that I can not put yet, maybe in future.

**Comment by sopla4ever** [comment]
Thank you for this suggestions. I will do that with separate branches.
Github for me is quite new :(

I know that some commits are not related to privacy/security but can you make separate category like "Non privacy/security related"?
I have a dream that I can use one script/tool to manage all I need  like One Ring to rule them all.

**Comment by undergroundwires** [comment]
Hi @sopla4ever , a quick update. Time to make your dreams real 😀 I back off from my decision and I will add the category that you mention. So reopening this PR as it will eventually get merged.

**Comment by undergroundwires** [comment]
Hi @sopla4ever , a quick update. Time to make your dreams real 😀 I back off from my decision and I will add the category that you mention. Feel free to check #56 to see how we decided on going implementing the decision. Once the category is there I'll update your PR and merge it.

Thanks again for all of  your contributions ♥

**Review by its0x08 — APPROVED** [review]

**Comment by femdiya** [comment]
@undergroundwires
Is there any updates for this PR?
Because on last comment you mentioned issue #56 which is closed by now.
So is there any plans on merging this one or you just wanna close it?

**Comment by undergroundwires** [comment]
Current status: Unfortunately I never had the time to add this, or maintain, even though I attempted it. So privacy scripts only until I have more time.

**Pull request closed without merging**
