### PR TITLE
Fixed Some More typos

### PR DESCRIPTION
**Pull request by Disk2019**
Kindly cross check & approve

### CODE REVIEW

**Comment by undergroundwires** [comment]
LGTM. So many mistakes I never knew existed. Thank you, the tool is much better now!

**Comment by Disk2019** [comment]
Brother now it looks super duper clean script . we must look forward to add more options into it from now onwards to make it {AIO} All in One Debloat , Privacy & Telemetry Script For Online Win10 all SKU's plus worked great with $OEM$ Installation setupcomplete method too.
Please Do have a look at my attachment. Thanks a lot lot again n again for releasing such a great script project .
[Extra.reg.txt](https://github.com/undergroundwires/privacy.sexy/files/4850104/Extra.reg.txt)

**Comment by undergroundwires** [comment]
@Disk2019 Awesome. I've analyzed the file & found batch commands and checked if they exist in the scripts in #16.

Can you review PR where I add them and check if they look good in #17?

**Comment by Disk2019** [comment]
Dear Brother i have hundreds of reg files & i am working on privacy script downloaded from your domain to make it All in One Debloat , Privacy & Telemetry Script accroding to my needs for 100 percent debloated private & hardend win10 plus which will work as $OEM$ setupcomplete cmd method too for clean win10 installation which will perfectly work in a private environment.

One more request to be taken under review :
:: ----------------------------------------------------------
:: ------------ Remove Onedrive & All Traces-----------------
:: ----------------------------------------------------------
echo --- Remove OneDrive and All Traces for clean install
Taskkill /F /IM OneDrive.exe
%SystemRoot%\System32\OneDriveSetup.exe /uninstall
%SystemRoot%\SysWOW64\OneDriveSetup.exe /uninstall
rd "%UserProfile%\OneDrive" /Q /S
rd "%LocalAppData%\Microsoft\OneDrive" /Q /S
rd "%ProgramData%\Microsoft OneDrive" /Q /S
rd "C:\OneDriveTemp" /Q /S
reg delete "HKEY_CLASSES_ROOT\CLSID\{018D5C66-4533-4307-9B53-224DE2ED1FE6}" /f
reg delete "HKEY_CLASSES_ROOT\Wow6432Node\CLSID\{018D5C66-4533-4307-9B53-224DE2ED1FE6}" /f
:: ----------------------------------------------------------

:: ----------------------------------------------------------
:: --------------------Disable Unwanted Features----------
:: ----------------------------------------------------------
echo --- Disable Features for clean install
Dism /online /Disable-Feature /FeatureName:"SMB1Protocol"
Dism /online /Disable-Feature /FeatureName:"MicrosoftWindowsPowerShellV2Root"
Dism /online /disable-feature /featurename:"SmbDirect"
Dism /online /disable-feature /featurename:"Printing-XPSServices-Features"
Dism /online /disable-feature /featurename:"Printing-Foundation-Features"
Dism /online /disable-feature /featurename:"Printing-Foundation-InternetPrinting-Client"
Dism /online /disable-feature /featurename:"WorkFolders-Client"
Dism /online /disable-feature /featurename:"WCF-TCP-PortSharing45"
Dism /online /disable-feature /featurename:"MSRDC-Infrastructure"
Dism /online /disable-feature /featurename:"MediaPlayback"
:: ----------------------------------------------------------

:: ----------------------------------------------------------
:: --------------------Remove Printers-----------------------
:: ----------------------------------------------------------
echo --- Remove Extra Printers and Set Print to PDF as Default printer
printui.exe /dl /n "Fax"
printui.exe /dl /n "Microsoft XPS Document Writer"
wmic printer where name="Microsoft Print to PDF" call setdefaultprinter
:: ----------------------------------------------------------

Turn Hibernate off on clean install 
powercfg -h off

Set reserved storage disabled on clean install
DISM /online /Set-ReservedStorageState /State:Disabled

theres a lot lot more to be added its just a beginning  from my side.
please reveiew my requests & add them so that one day our script will be famous in global for all in one deblot privacy telemetry script. i will be adding scripts every week on sunday night according to my time zone.
thanks a lot lot again.

**Pull request merged**
